# Generated by Django 6.0.4 on 2026-05-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senhaInstitucional', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('scoreConformidade', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('scoreConformidade', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senhaInstitucional', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senhaInstitucional', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('scoreConformidade', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('conceitoFinal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivoUrl', models.FileField(upload_to='modelos/')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_documentos', to='app.aluno')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='ParecerTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='app.professor')),
            ],
            options={
                'verbose_name': 'Parecer Técnico',
                'verbose_name_plural': 'Pareceres Técnicos',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('idAssinatura', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Assinatura')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('ipAcesso', models.GenericIPAddressField(verbose_name='IP Acesso')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.aluno', verbose_name='Aluno')),
                ('apolice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.apolice')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contrato')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.coordenador', verbose_name='Coordenador')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.professor', verbose_name='Professor')),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.relatorio')),
            ],
            options={
                'verbose_name': 'Assinatura digital',
                'verbose_name_plural': 'Assinaturas digitais',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('RETIFICACAO_SOLICITADA', 'Retificação solicitada')], default='PENDENTE', max_length=30)),
                ('motivo_retificacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.aluno')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to='app.coordenador')),
            ],
            options={
                'verbose_name': 'Solicitação de Estágio',
                'verbose_name_plural': 'Solicitações de Estágio',
            },
        ),
        migrations.AddField(
            model_name='relatorio',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
        ),
        migrations.AddField(
            model_name='apolice',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
        ),
    ]
