<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-22 05:11
=======
# Generated by Django 6.0.4 on 2026-06-12 01:03
>>>>>>> upstream/main

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> upstream/main
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivoUrl', models.FileField(upload_to='modelos/')),
<<<<<<< HEAD
=======
                ('campos_dinamicos', models.JSONField(default=list, help_text="Exemplo: [{'id': 'nome_empresa', 'label': 'Nome da Empresa', 'tipo': 'text'}, {'id': 'carga_horaria', 'label': 'Carga Horária (h)', 'tipo': 'number'}]")),
>>>>>>> upstream/main
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('conceitoFinal', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('APROVADO_RESSALVAS', 'Aprovado com ressalvas')], max_length=30, null=True, verbose_name='Conceito Final')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> upstream/main
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_coordenador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='ParecerTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='app.professor')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='app.relatorio')),
            ],
            options={
                'verbose_name': 'Parecer Técnico',
                'verbose_name_plural': 'Pareceres Técnicos',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('ipAcesso', models.GenericIPAddressField(verbose_name='IP Acesso')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.aluno', verbose_name='Aluno')),
                ('apolice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.apolice')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contrato')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.coordenador', verbose_name='Coordenador')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.professor', verbose_name='Professor')),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='app.relatorio')),
            ],
            options={
                'verbose_name': 'Assinatura digital',
                'verbose_name_plural': 'Assinaturas digitais',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> upstream/main
            name='SolicitacaoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('RETIFICACAO_SOLICITADA', 'Retificação solicitada')], default='PENDENTE', max_length=30)),
                ('motivo_retificacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.aluno')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to='app.coordenador')),
            ],
            options={
                'verbose_name': 'Solicitação de Estágio',
                'verbose_name_plural': 'Solicitações de Estágio',
            },
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='relatorio',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
        ),
        migrations.AddField(
            model_name='apolice',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio'),
=======
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).')),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('conceitoFinal', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('APROVADO_RESSALVAS', 'Aprovado com ressalvas')], max_length=30, null=True, verbose_name='Conceito Final')),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Preenchido quando o coordenador rejeita o relatório.', null=True, verbose_name='Motivo da rejeição')),
                ('modelo_origem', models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).')),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Preenchido quando o coordenador rejeita o documento.', null=True, verbose_name='Motivo da rejeição')),
                ('modelo_origem', models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).')),
                ('scoreConformidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('modelo_origem', models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio')),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
            },
>>>>>>> upstream/main
        ),
    ]
