# Generated by Django 6.0.4 on 2026-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolice',
            name='scoreConformidade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='scoreConformidade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='scoreConformidade',
            field=models.FloatField(default=0.0),
        ),
    ]
