# Generated by Django 6.0.4 on 2026-06-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelodocumento_campos_dinamicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='apolice',
            name='modelo_origem',
            field=models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo_origem',
            field=models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='modelo_origem',
            field=models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento'),
        ),
    ]
