# Generated by Django 6.0.4 on 2026-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apolice_modelo_origem_contrato_modelo_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolice',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
    ]
