# Generated by Django 5.2 on 2026-06-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_databasefile_alter_aluno_id_alter_apolice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioIntermediario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('scoreConformidade', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).')),
                ('mes', models.CharField(choices=[('MES1', '1º Mês'), ('MES2', '2º Mês'), ('MES3', '3º Mês'), ('MES4', '4º Mês'), ('MES5', '5º Mês'), ('MES6', '6º Mês')], max_length=10)),
                ('feedback_coordenador', models.TextField(blank=True, null=True)),
                ('modelo_origem', models.ForeignKey(blank=True, help_text='Registra qual modelo dinâmico gerou este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodocumento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documentos', to='app.solicitacaoestagio')),
            ],
            options={
                'verbose_name': 'Relatório Intermediário',
                'verbose_name_plural': 'Relatórios Intermediários',
            },
        ),
    ]
