# Generated by Django 6.0.4 on 2026-06-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apolice_status_alter_contrato_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, help_text='Preenchido quando o coordenador rejeita o documento.', null=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AlterField(
            model_name='apolice',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('EM_ASSINATURA', 'Em assinatura'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDA', 'Concluída'), ('EM_REVISAO', 'Em revisão')], default='ENVIADO', max_length=30),
        ),
    ]
