# Generated by Django 6.0.4 on 2026-06-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contrato_motivo_rejeicao_alter_apolice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, help_text='Preenchido quando o coordenador rejeita o relatório.', null=True, verbose_name='Motivo da rejeição'),
        ),
    ]
