# Generated by Django 6.0.4 on 2026-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_relatorio_motivo_rejeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='apolice',
            name='dados',
            field=models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dados',
            field=models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='dados',
            field=models.JSONField(blank=True, default=dict, help_text='Respostas do formulário usadas para gerar o documento (base das análises).'),
        ),
    ]
