# Generated by Django 6.0.4 on 2026-06-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_apolice_dados_contrato_dados_relatorio_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parecertecnico',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='parecertecnico',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssinaturaDigital',
        ),
        migrations.DeleteModel(
            name='ParecerTecnico',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
